version: "3.9"

services:
  workspace:
    container_name: ${PROJECT_NAME:-original}-workspace
    build:
      context: ./docker/workspace
      args:
        USER_NAME: ${USER_NAME:-vscode}
        USER_GROUP_NAME: ${USER_GROUP_NAME:-workspace}
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
        JAVA_VERSION: ${JAVA_VERSION:-17.0.11-amzn}
        GRADLE_VERSION: ${GRADLE_VERSION:-8.8}
        KOTLIN_VERSION: ${KOTLIN_VERSION:-2.0.0}
        NODE_VERSION: ${NODE_VERSION:-18.18.0}
        LOCALE: ${LOCALE:-ja_JP.UTF-8}
    tty: true
    environment:
      TZ: ${TIME_ZONE:-Asia/Tokyo}
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-dev}
      DB_USER: ${DB_USER:-dbuser}
      DB_URL: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
      DB_PASSWORD: ${DB_PASSWORD:-thisIsReallyStrongPassword123}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-thisIsReallyStrongPassword123}
      DB_DRIVER: ${DB_DRIVER:-org.postgresql.Driver}
      # NGINX_PORT: ${NGINX_PORT:-3333}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-password}
      KEYCLOAK_HTTP_PORT: ${KEYCLOAK_HTTP_PORT:-8080}
      REALM_NAME: ${REALM_NAME:-auth-hands-on}
      BACKEND_CLIENT_ID: ${BACKEND_CLIENT_ID:-auth-hands-on-api}
      FRONTEND_CLIENT_ID: ${FRONTEND_CLIENT_ID:-auth-hands-on-client}
      BACKEND_CLIENT_SECRET: ${BACKEND_CLIENT_SECRET:-sample-secret}
      FRONTEND_CLIENT_SECRET: ${FRONTEND_CLIENT_SECRET:-sample-secret}
      REDIRECT_URIS: ${REDIRECT_URIS:-http://localhost:2222/gettoken}
      ORIGIN_URIS: ${ORIGIN_URIS:-http://localhost:2222}
      GIT_USER: ${GIT_USER:-user}
      GIT_EMAIL: ${GIT_EMAIL:-email}
    volumes:
      - ../:/home/${USER_NAME:-vscode}/workspace:cached
      - ~/.aws:/home/${USER_NAME:-vscode}/.aws
    ports:
      - ${WORKSPACE_PORT:-9999}:9999

  postgres:
    container_name: ${PROJECT_NAME:-original}-postgres
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER:-dbuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-thisIsReallyStrongPassword123}
      POSTGRES_DB: ${DB_NAME:-dev}
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - ../.docker/postgres:/var/lib/postgresql/data/
    restart: unless-stopped

  # nginx:
  #   build:
  #     context: ./docker/nginx
  #   container_name: ${PROJECT_NAME:-original}-nginx
  #   ports:
  #     - ${NGINX_PORT:-3333}:80
  #   volumes:
  #     - ./docker/nginx/conf.d:/etc/nginx/conf.d

  # endpoinrt http://localhost:8080/admin/master/console/
  keycloak:
    image: bitnami/keycloak:25
    container_name: ${PROJECT_NAME:-original}-keycloak
    ports: 
      - ${KEYCLOAK_HTTP_PORT:-8080}:8080
    restart: always
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-password}
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_NAME: ${DB_NAME:-dev}
      KEYCLOAK_DATABASE_USER: ${DB_USER:-dbuser}
      KEYCLOAK_DATABASE_PASSWORD: ${DB_PASSWORD:-thisIsReallyStrongPassword123}
      KEYCLOAK_LOG_LEVEL: ${KEYCLOAK_LOG_LEVEL:-info}
      KEYCLOAK_EXTRA_ARGS: --import-realm
      REALM_NAME: ${REALM_NAME:-auth-hands-on}
      BACKEND_CLIENT_ID: ${BACKEND_CLIENT_ID:-auth-hands-on-api}
      FRONTEND_CLIENT_ID: ${FRONTEND_CLIENT_ID:-auth-hands-on-client}
      BACKEND_CLIENT_SECRET: ${BACKEND_CLIENT_SECRET:-sample-secret}
      FRONTEND_CLIENT_SECRET: ${FRONTEND_CLIENT_SECRET:-sample-secret}
      REDIRECT_URIS: ${REDIRECT_URIS:-http://localhost:2222/gettoken}
      ORIGIN_URIS: ${ORIGIN_URIS:-http://localhost:2222}
    volumes:
      - .devcontainer/docker/keycloak/realms:/opt/bitnami/keycloak/data/import
    depends_on:
      - postgres
