@host = {{hostname}}:{{port}}

# / GET request
GET http://{{host}}/api/v1/
Accept: text/plain

###

# / GET request

@name = min

GET http://{{host}}/api/v1/hello?name={{name}}
Accept: application/json

###

GET http://{{host}}/api/v1/hello/{{name}}
Accept: application/json

###

POST http://{{host}}/api/v1/hello
Accept: application/json
Content-type: application/json; charset=utf-8

{
    "name": "{{name}}"
}
###